
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    depends_on:
      - db
    env_file:
      - .env
    # environment:
    #   - DB_HOST=db
    #   - DB_NAME=mydb
    #   - DB_USER=user
    #   - DB_PASS=password

volumes:
  mysql_data:
